{% set name = "openpulse" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openpulse-{{ version }}.tar.gz
    sha256: 4c184e3012907ec35f04202ed72621037b1a06d70195769576bfc9e62c01bf94
  - url: https://raw.githubusercontent.com/openqasm/openpulse-python/v{{ version }}/LICENSE
    sha256: 5d24d1bf838a90bd88ba223b3d64bebb260ec6e52300dc5df3ed8f1ee9f8723e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.7
    - antlr4-python3-runtime <4.14,>=4.7
    - openqasm3 <2.0,>=1.0.0
    - importlib-metadata

test:
  imports:
    - openpulse
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/openqasm/openpulse/
  summary: Reference OpenPulse AST in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
